name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: tomkaboris/cv_tomkaboris@v1.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cv_tomkaboris:$(date +%s)
