name: Build and push Docker image upon release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/cv_tomkaboris
          
      - name: Push Docker image
        run: |
          docker tag cv_tomkaboris ${{ secrets.DOCKERHUB_USERNAME }}/cv_tomkaboris
          docker push boristomka/cv_tomkaboris:latest
